### ISSUE TITLE
Official wallet crashing after install when launching on macOs 10.13.4

### ISSUE THREAD

**Issue by chisNaN** [deeponion/deeponion-legacy#96] opened 2018-04-21 07:03 UTC
Hello.
Sorry i dont know where to post this issue but if the official wallet is working on windows 10 its not launching on macOS 10.13.4 with the following report:

```
Process:               DeepOnion-Qt [652]
Path:                  /Applications/DeepOnion-Qt.app/Contents/MacOS/DeepOnion-Qt
Identifier:            org.deeponion.DeepOnion-Qt
Version:               1.6.2 (1.6.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           DeepOnion-Qt [652]
User ID:               501

Date/Time:             2018-04-21 09:02:17.253 +0200
OS Version:            Mac OS X 10.13.4 (17E199)
Report Version:        12
Anonymous UUID:        4ED956D5-08B9-167C-BA6C-5173EDE68956


Time Awake Since Boot: 3500 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
  Reason: image not found

Binary Images:
       0x10445c000 -        0x104b7efff +org.deeponion.DeepOnion-Qt (1.6.2 - 1.6.2) <ACC84206-56D4-3CFC-8D57-8B027F1361A7> /Applications/DeepOnion-Qt.app/Contents/MacOS/DeepOnion-Qt
       0x104c87000 -        0x104c89ff7 +libboost_system.dylib (0) <5CFD618D-2AF4-3C59-88C2-B0CE6CCA7265> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x104c94000 -        0x104ca2fff +libboost_filesystem.dylib (0) <E0F26994-D113-3440-9645-6E4FB91ABF19> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x104cad000 -        0x104cddfff +libboost_program_options-mt.dylib (0) <4280CB1D-C6B9-350D-B89E-5BBFFEBE8896> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x104d01000 -        0x104d0dff7 +libboost_thread.dylib (0) <FD27C445-A73B-392A-B7C7-7A9C419BA0C8> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_thread.dylib
       0x104d19000 -        0x104d1bfff +libboost_chrono-mt.dylib (0) <8FA281FE-6D12-3E2C-A7DE-F851F9C23F53> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x104d22000 -        0x104e25ff3 +QtNetwork (0) <DD8EF1B7-0C03-386D-AE11-E618BC4C87F3> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x104e72000 -        0x10529eff7 +QtWidgets (0) <AD15E490-1C7E-344F-9B40-A684A9160882> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x105406000 -        0x105833ff7 +QtGui (0) <96CF196B-1BBB-317F-9F39-86DD41787FC9> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10592e000 -        0x105e0ffff +QtCore (0) <0967D4C1-9487-3421-9861-304DEE848576> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x105ec9000 -        0x105f23ff7 +QtDBus (0) <6BFE4F79-D9C9-381E-A68D-BB5E6FFEDF4E> /Applications/DeepOnion-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x105f3d000 -        0x10606fff7 +libprotobuf.15.dylib (0) <7126DB9C-1EE3-36D1-B366-9047D43A8A3C> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x106121000 -        0x106239feb +libdb_cxx-4.8.dylib (0) <A513D80B-6037-3066-B163-C800B68C9019> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x106265000 -        0x106275ff3 +libz.1.dylib (0) <ACB7269B-A127-30F2-8EE4-1F6E0B286AF1> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libz.1.dylib
       0x10627d000 -        0x1062a9ff7 +libevent-2.1.6.dylib (0) <B4866E97-7CC4-3E15-BF2C-F667971CE7C7> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x1062bd000 -        0x1062c5ff7 +libminiupnpc.16.dylib (0) <062F4A0E-32DB-36B6-B504-8734C0E61FB2> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x1062cb000 -        0x106315ff7 +libssl.1.0.0.dylib (0) <FFB2C5A8-1496-3CCD-A72B-B99C228CF433> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x106338000 -        0x1064bd91f +libcrypto.1.0.0.dylib (0) <09C0330E-76BF-302A-9549-AC02D38B87D0> /Applications/DeepOnion-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x10a323000 -        0x10a36d9df  dyld (551.3) <AFAB4EFA-7020-34B1-BBEF-0F26C6D3CA36> /usr/lib/dyld
    0x7fff4c9aa000 -     0x7fff4d808fff  com.apple.AppKit (6.9 - 1561.40.112) <C839B0C1-F7EE-3056-985C-63CF1A030EC4> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4d85a000 -     0x7fff4d85afff  com.apple.ApplicationServices (48 - 50) <8DA47D38-B07B-3AE2-B343-4579864430C6> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff4f3cb000 -     0x7fff4f86cfef  com.apple.CoreFoundation (6.9 - 1452.23) <945E5C0A-86C5-336E-A64F-5BF06E78985A> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff50537000 -     0x7fff50537fff  com.apple.CoreServices (822.31 - 822.31) <615919A2-AE11-3F27-9A37-FB0CFF8D36B6> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff5151f000 -     0x7fff518e5fff  com.apple.Foundation (6.9 - 1452.23) <E64540AD-1755-3C16-8537-552A00E92541> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff74f4f000 -     0x7fff74f82ff7  libclosured.dylib (551.3) <DC3DA678-9C40-339C-A9C6-32AB74FCC682> /usr/lib/closure/libclosured.dylib
    0x7fff75489000 -     0x7fff7548affb  libSystem.B.dylib (1252.50.4) <C7810EA7-A61F-3817-8E54-E2EC4E26F946> /usr/lib/libSystem.B.dylib
    0x7fff756be000 -     0x7fff75714fff  libc++.1.dylib (400.9) <7D3DACCC-3804-393C-ABC1-1A580FD00CB6> /usr/lib/libc++.1.dylib
    0x7fff75715000 -     0x7fff75739ff7  libc++abi.dylib (400.8.2) <EF5E37D7-11D9-3530-BE45-B986612D13E2> /usr/lib/libc++abi.dylib
    0x7fff76b38000 -     0x7fff76f267e7  libobjc.A.dylib (723) <DD9E5EC5-B507-3249-B700-93433E2D5EDF> /usr/lib/libobjc.A.dylib
    0x7fff775fc000 -     0x7fff77600ff7  libcache.dylib (80) <092479CB-1008-3A83-BECF-E115F24D13C1> /usr/lib/system/libcache.dylib
    0x7fff77601000 -     0x7fff7760bff3  libcommonCrypto.dylib (60118.50.1) <029F5985-9B6E-3DCB-9B96-FD007678C6A7> /usr/lib/system/libcommonCrypto.dylib
    0x7fff7760c000 -     0x7fff77613fff  libcompiler_rt.dylib (62) <968B8E3F-3681-3230-9D78-BB8732024F6E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff77614000 -     0x7fff7761dffb  libcopyfile.dylib (146.50.5) <3885083D-50D8-3EEC-B481-B2E605180D7F> /usr/lib/system/libcopyfile.dylib
    0x7fff7761e000 -     0x7fff776a3fff  libcorecrypto.dylib (562.50.17) <67007279-24E1-3F30-802D-A55CD5C27946> /usr/lib/system/libcorecrypto.dylib
    0x7fff7772b000 -     0x7fff77764ff7  libdispatch.dylib (913.50.12) <848EEE57-4235-3A61-9A52-C0097DD2AB5E> /usr/lib/system/libdispatch.dylib
    0x7fff77765000 -     0x7fff77782ff7  libdyld.dylib (551.3) <CF59A5A5-288B-30E6-BD42-9056B4E4139A> /usr/lib/system/libdyld.dylib
    0x7fff77783000 -     0x7fff77783ffb  libkeymgr.dylib (28) <E34E283E-90FA-3C59-B48E-1277CDB9CDCE> /usr/lib/system/libkeymgr.dylib
    0x7fff77791000 -     0x7fff77791ff7  liblaunch.dylib (1205.50.76) <4D52BB64-C568-3A36-8935-2480427EE2A2> /usr/lib/system/liblaunch.dylib
    0x7fff77792000 -     0x7fff77796ffb  libmacho.dylib (906) <1902A611-081A-3452-B11E-EBD1B166E831> /usr/lib/system/libmacho.dylib
    0x7fff77797000 -     0x7fff77799ff3  libquarantine.dylib (86) <26C0BA22-8F93-3A07-9A4E-C8D53D2CE42E> /usr/lib/system/libquarantine.dylib
    0x7fff7779a000 -     0x7fff7779bff3  libremovefile.dylib (45) <711E18B2-5BBE-3211-A916-56740C27D17A> /usr/lib/system/libremovefile.dylib
    0x7fff7779c000 -     0x7fff777b3fff  libsystem_asl.dylib (356.50.1) <3B24F2D1-B578-359D-ADB2-0ED19A364C38> /usr/lib/system/libsystem_asl.dylib
    0x7fff777b4000 -     0x7fff777b4fff  libsystem_blocks.dylib (67) <17303FDF-0D2D-3963-B05E-B4DF63052D47> /usr/lib/system/libsystem_blocks.dylib
    0x7fff777b5000 -     0x7fff7783eff7  libsystem_c.dylib (1244.50.9) <1187BFE8-4576-3247-8177-481554E1F9E7> /usr/lib/system/libsystem_c.dylib
    0x7fff7783f000 -     0x7fff77842ffb  libsystem_configuration.dylib (963.50.8) <DF6B5287-203E-30CB-9947-78DF446C72B8> /usr/lib/system/libsystem_configuration.dylib
    0x7fff77843000 -     0x7fff77846ffb  libsystem_coreservices.dylib (51) <486000D3-D8CB-3BE7-8EE5-8BF380DE6DF7> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff77847000 -     0x7fff77848fff  libsystem_darwin.dylib (1244.50.9) <09C21A4A-9EE0-388B-A9D9-DFF8F6758791> /usr/lib/system/libsystem_darwin.dylib
    0x7fff77849000 -     0x7fff7784fff7  libsystem_dnssd.dylib (878.50.17) <9033B909-BCF7-37EB-A040-ADE8081611D6> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff77850000 -     0x7fff77899ff7  libsystem_info.dylib (517.30.1) <AB634A98-B8AA-3804-8436-38261FC8EC4D> /usr/lib/system/libsystem_info.dylib
    0x7fff7789a000 -     0x7fff778c0ff7  libsystem_kernel.dylib (4570.51.1) <5CAAB092-02CC-3A37-9D5F-C4AD1083AB96> /usr/lib/system/libsystem_kernel.dylib
    0x7fff778c1000 -     0x7fff7790cfcb  libsystem_m.dylib (3147.50.1) <FC2E58BA-E6D5-3D2A-89CA-67F212294136> /usr/lib/system/libsystem_m.dylib
    0x7fff7790d000 -     0x7fff7792cfff  libsystem_malloc.dylib (140.50.6) <7FD43735-9DDD-300E-8C4A-F909A74BDF49> /usr/lib/system/libsystem_malloc.dylib
    0x7fff7792d000 -     0x7fff77a5dff3  libsystem_network.dylib (1229.51.2) <F65ED095-8ABA-3355-93F8-B9D0505932F4> /usr/lib/system/libsystem_network.dylib
    0x7fff77a5e000 -     0x7fff77a68ffb  libsystem_networkextension.dylib (767.50.25) <758F1414-796D-3422-83C9-92D2915A06CE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff77a69000 -     0x7fff77a72ff3  libsystem_notify.dylib (172) <08012EC0-2CD2-34BE-BF93-E7F56491299A> /usr/lib/system/libsystem_notify.dylib
    0x7fff77a73000 -     0x7fff77a7aff7  libsystem_platform.dylib (161.50.1) <6355EE2D-5456-3CA8-A227-B96E8F1E2AF8> /usr/lib/system/libsystem_platform.dylib
    0x7fff77a7b000 -     0x7fff77a86fff  libsystem_pthread.dylib (301.50.1) <0E51CCBA-91F2-34E1-BF2A-FEEFD3D321E4> /usr/lib/system/libsystem_pthread.dylib
    0x7fff77a87000 -     0x7fff77a8afff  libsystem_sandbox.dylib (765.50.51) <B48D256E-D7DB-3D4F-BC95-34557170C7AA> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff77a8b000 -     0x7fff77a8cff3  libsystem_secinit.dylib (30) <DE8D14E8-A276-3FF8-AE13-77F7040F33C1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff77a8d000 -     0x7fff77a94ff7  libsystem_symptoms.dylib (820.50.37) <ED7350E0-B68B-374A-9AB7-DC1F195A8327> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff77a95000 -     0x7fff77aa8fff  libsystem_trace.dylib (829.50.17) <6568D68B-1D4C-38EE-90A9-54821D6403C0> /usr/lib/system/libsystem_trace.dylib
    0x7fff77aaa000 -     0x7fff77aafff7  libunwind.dylib (35.3) <BEF3FB49-5604-3B5F-82B5-332B80023AC3> /usr/lib/system/libunwind.dylib
    0x7fff77ab0000 -     0x7fff77addfff  libxpc.dylib (1205.50.76) <25DB244E-217D-3CE0-A8F2-0C4255783B42> /usr/lib/system/libxpc.dylib

Model: MacBook10,1, BootROM MB101.0160.B00, 2 processors, Intel Core i5, 1,3 GHz, 8 GB, SMC 2.42f10
Graphics: Intel HD Graphics 615, Intel HD Graphics 615, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 1867 MHz, 0x80CE, 0x4B33514634463430424D2D41474346202020
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 1867 MHz, 0x80CE, 0x4B33514634463430424D2D41474346202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x168), Broadcom BCM43xx 1.0 (7.77.37.29.1a7)
Bluetooth: Version 6.0.5f3, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
Thunderbolt Bus: 
```

**Comment by brakmic** [comment] 2018-04-21 08:17
Duplicate of [https://github.com/deeponion/deeponion/issues/95](https://github.com/deeponion/deeponion/issues/95#issuecomment-383065035)

**Closed as completed by brakmic** 2018-04-21 08:17 UTC
